name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Greeting
        run: |
            echo "Hello IBRAR"
            echo "Hello Ayesha"
      - name: Print GoodBye
        run: echo "Done - Bye!!"
